# Generated by Django 3.2 on 2023-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='OF8MHOEBHITZ', max_length=50, null=True, verbose_name='Код подтверждения'),
        ),
    ]
