# Generated by Django 3.2 on 2023-03-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230302_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='THG4HV1HNV7W', max_length=50, null=True, verbose_name='Код подтверждения'),
        ),
    ]
